name: space_game
description: Space Miner PWA built with Flutter and Flame
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter
  flame: 1.32.0
  flame_audio: 2.11.10
  shared_preferences: 2.5.3
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/enemies/
    - assets/images/enemies/faction1/
    - assets/images/enemies/faction2/
    - assets/images/enemies/faction3/
    - assets/images/enemies/faction4/
    - assets/images/players/
    - assets/images/asteroids/
    - assets/images/icons/
    - assets/images/explosions/
    - assets/audio/
    - assets/fonts/
