name: Analyze and Test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    env:
      PUB_CACHE: ${{ github.workspace }}/.pub-cache
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: .tooling/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('scripts/bootstrap_flutter.sh') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install dependencies
        run: mkdir -p $PUB_CACHE && ./scripts/flutterw pub get
      - name: Analyze
        run: |
          set -o pipefail
          ./scripts/flutterw analyze | tee analyze.log
          exit_code=${PIPESTATUS[0]}
          {
            echo "### Analyze"
            echo '```'
            cat analyze.log
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          exit $exit_code
      - name: Test
        run: |
          set -o pipefail
          ./scripts/flutterw test | tee test.log
          exit_code=${PIPESTATUS[0]}
          {
            echo "### Test"
            echo '```'
            cat test.log
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
          exit $exit_code
