name: CI

on:
  pull_request:

jobs:
  format-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Format
        run: dart format .
      - name: Commit formatted code
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'chore: apply dart format'
      - name: Analyze
        run: flutter analyze
