name: CI

on:
  pull_request:

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    env:
      PUB_CACHE: ~/.pub-cache
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: .tooling/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('scripts/bootstrap_flutter.sh') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Analyze
        run: ./scripts/flutterw analyze
      - name: Test
        run: ./scripts/flutterw test
